#!/usr/bin/env python3
"""Tests for the structure scanner in code-craft.

The scanner measures function length, nesting depth and parameter count by
reading indentation and counting braces. The measurements that are easy to get
wrong are the ones checked hardest here: nesting must count block depth rather
than distinct indent columns, and a triple quoted docstring must not count as
code. Source files are written into a temporary directory and removed after.

Run with: python3 tests/test_structure_scan.py
"""

from __future__ import annotations

import importlib.util
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SCRIPT = ROOT / "skills" / "code-craft" / "scripts" / "structure_scan.py"

spec = importlib.util.spec_from_file_location("structure_scan", SCRIPT)
assert spec and spec.loader, "cannot load scanner at %s" % SCRIPT
structure_scan = importlib.util.module_from_spec(spec)
sys.modules["structure_scan"] = structure_scan
spec.loader.exec_module(structure_scan)

failures: list[str] = []


def check(condition: bool, message: str) -> None:
    if condition:
        print("  pass  %s" % message)
    else:
        print("  FAIL  %s" % message)
        failures.append(message)


def rules_for(path: Path, overrides=None) -> list:
    result = structure_scan.scan_file(path, overrides or {}, False)
    return [] if result is None else result[1]


def has_rule(findings, rule: str) -> bool:
    return any(f.rule == rule for f in findings)


def write(root: Path, name: str, text: str) -> Path:
    path = root / name
    path.write_text(text, encoding="utf-8")
    return path


def long_python(lines: int) -> str:
    body = "\n".join("    a%d = %d" % (n, n) for n in range(lines))
    return "def big():\n%s\n" % body


def deep_dict_python() -> str:
    return (
        "def shallow():\n"
        "    config = {\n"
        "        'a': 1,\n"
        "        'b': 2,\n"
        "        'c': 3,\n"
        "        'd': 4,\n"
        "    }\n"
        "    return config\n"
    )


def deep_nest_python() -> str:
    return (
        "def deep(flag):\n"
        "    if flag:\n"
        "        for i in range(3):\n"
        "            while i:\n"
        "                if i > 1:\n"
        "                    i -= 1\n"
        "    return flag\n"
    )


with tempfile.TemporaryDirectory() as tmp:
    root = Path(tmp)

    print("python function length")
    over = write(root, "over.py", long_python(60))
    check(has_rule(rules_for(over), "function-length"),
          "a 60 line function is reported over the 50 line budget")
    under = write(root, "under.py", long_python(10))
    check(not has_rule(rules_for(under), "function-length"),
          "a 10 line function is not reported")

    print("\nnesting counts blocks, not indent columns")
    dict_file = write(root, "dict.py", deep_dict_python())
    check(not has_rule(rules_for(dict_file), "nesting-depth"),
          "a multi line dict literal is not counted as nesting")
    nested = write(root, "nested.py", deep_nest_python())
    check(has_rule(rules_for(nested), "nesting-depth"),
          "four nested blocks are reported over the depth 3 budget")

    print("\ndocstrings do not count as code lines")
    docstring = '    """%s"""\n' % ("filler line\n" * 60)
    body = "def documented():\n" + docstring + "    return 1\n"
    doc_file = write(root, "doc.py", body)
    check(not has_rule(rules_for(doc_file), "function-length"),
          "a big triple quoted docstring does not inflate code lines")

    print("\nbrace language measurement")
    js = (
        "function big() {\n"
        + "  let a = 1;\n" * 60
        + "}\n"
    )
    js_file = write(root, "big.js", js)
    check(has_rule(rules_for(js_file), "function-length"),
          "a long JavaScript function is reported over its budget")
    js_deep = (
        "function deep(flag) {\n"
        "  if (flag) {\n"
        "    for (;;) {\n"
        "      while (flag) {\n"
        "        if (flag) {\n"
        "          flag = false;\n"
        "        }\n"
        "      }\n"
        "    }\n"
        "  }\n"
        "}\n"
    )
    js_deep_file = write(root, "deep.js", js_deep)
    check(has_rule(rules_for(js_deep_file), "nesting-depth"),
          "deeply nested JavaScript braces are reported over the depth budget")

    print("\nparameter count")
    params = "def many(a, b, c, d, e, f):\n    return a\n"
    params_file = write(root, "params.py", params)
    check(has_rule(rules_for(params_file), "parameter-count"),
          "six parameters are reported over the 5 parameter budget")

    print("\ngenerated files are skipped")
    gen = "# Code generated by tool. DO NOT EDIT.\n" + long_python(60)
    gen_file = write(root, "gen.py", gen)
    check(rules_for(gen_file) == [] and structure_scan.scan_file(gen_file, {}, False) is None,
          "a generated-file marker in the first five lines skips the file")

    print("\ncommand line overrides")
    small = write(root, "small.py", long_python(30))
    findings = rules_for(small, {"function": 20})
    check(has_rule(findings, "function-length"),
          "--max-function 20 turns a 30 line function into a finding")
    default = rules_for(small, {})
    check(not has_rule(default, "function-length"),
          "the same function is within the default budget")
    rc = structure_scan.main([str(small), "--max-function", "20", "--quiet"])
    check(rc == 1, "main exits 1 when --max-function forces a finding")
    rc_clean = structure_scan.main([str(small), "--quiet"])
    check(rc_clean == 0, "main exits 0 when nothing is over budget")

print("\n%d check(s) failed" % len(failures))
sys.exit(1 if failures else 0)
