#!/usr/bin/env python3
"""Report source files and functions that sit over their structure budget.

Measures four things per file: code lines, function length, nesting depth, and
parameter count. Defaults per language come from ../references/budgets.md and can
be overridden on the command line.

Supported extensions:
  .py .js .jsx .ts .tsx .mjs .cjs .go .java .kt .cs .rs .rb .php .c .h .cc .cpp
  .hpp .swift .sh .bash

This reads indentation and counts braces instead of parsing, so it miscounts
multi-line strings in some languages and heavily macro driven code. Treat a
finding as a reason to look at the file, not as a verdict.

Exit codes:
  0  nothing over budget
  1  at least one finding
  2  usage error

Usage:
  python3 structure_scan.py src/
  python3 structure_scan.py src/ --max-file 300 --max-function 40 --max-depth 3
  python3 structure_scan.py . --ext py,ts --json
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from dataclasses import dataclass
from pathlib import Path

# Per language budget and syntax description. "indent" languages close a block by
# returning to a lower indent column; "brace" languages close it with a brace.
LANGUAGES: dict[str, dict] = {
    "python": {
        "ext": (".py",),
        "block": "indent",
        "line_comment": "#",
        "budget": (400, 50, 3, 5),
        "func": re.compile(r"^(?P<indent>\s*)(?:async\s+)?def\s+(?P<name>[A-Za-z_]\w*)\s*\("),
    },
    "javascript": {
        "ext": (".js", ".jsx", ".ts", ".tsx", ".mjs", ".cjs"),
        "block": "brace",
        "line_comment": "//",
        "budget": (300, 40, 3, 4),
        "func": re.compile(
            r"^(?P<indent>\s*)(?:export\s+)?(?:default\s+)?(?:async\s+)?"
            r"(?:function\s*\*?\s*(?P<name>[A-Za-z_$][\w$]*)?\s*\("
            r"|(?:const|let|var)\s+(?P<name2>[A-Za-z_$][\w$]*)\s*=\s*"
            r"(?:async\s*)?(?:function\s*\*?\s*\(|\()"
            r"|(?P<name3>[A-Za-z_$][\w$]*)\s*\([^;=]*\)\s*(?::[^{;]+)?\{)"
        ),
    },
    "go": {
        "ext": (".go",),
        "block": "brace",
        "line_comment": "//",
        "budget": (500, 60, 3, 5),
        "func": re.compile(r"^(?P<indent>)func\s+(?:\([^)]*\)\s*)?(?P<name>[A-Za-z_]\w*)\s*\("),
    },
    "jvm": {
        "ext": (".java", ".kt", ".cs", ".swift"),
        "block": "brace",
        "line_comment": "//",
        "budget": (400, 45, 3, 5),
        "func": re.compile(
            r"^(?P<indent>\s*)(?:(?:public|private|protected|internal|static|final|"
            r"override|open|suspend|abstract|virtual|async|fun|func)\s+)+"
            r"(?:[\w<>\[\],.?]+\s+)?(?P<name>[A-Za-z_]\w*)\s*\([^;]*\)\s*(?:[:\w\s,]*)?\{"
        ),
    },
    "rust": {
        "ext": (".rs",),
        "block": "brace",
        "line_comment": "//",
        "budget": (500, 60, 3, 5),
        "func": re.compile(
            r"^(?P<indent>\s*)(?:pub(?:\([^)]*\))?\s+)?(?:const\s+|async\s+|unsafe\s+|extern\s+)*"
            r"fn\s+(?P<name>[A-Za-z_]\w*)"
        ),
    },
    "ruby": {
        "ext": (".rb",),
        "block": "indent",
        "line_comment": "#",
        "budget": (300, 30, 3, 4),
        "func": re.compile(r"^(?P<indent>\s*)def\s+(?P<name>[A-Za-z_][\w.]*[?!=]?)"),
    },
    "php": {
        "ext": (".php",),
        "block": "brace",
        "line_comment": "//",
        "budget": (400, 50, 3, 5),
        "func": re.compile(
            r"^(?P<indent>\s*)(?:(?:public|private|protected|static|final|abstract)\s+)*"
            r"function\s+(?P<name>[A-Za-z_]\w*)\s*\("
        ),
    },
    "c": {
        "ext": (".c", ".h", ".cc", ".cpp", ".hpp", ".hh", ".cxx"),
        "block": "brace",
        "line_comment": "//",
        "budget": (600, 60, 4, 6),
        "func": re.compile(
            r"^(?P<indent>)[A-Za-z_][\w\s\*&:<>,]*?(?P<name>[A-Za-z_]\w*)\s*\([^;]*\)\s*\{"
        ),
    },
    "shell": {
        "ext": (".sh", ".bash"),
        "block": "brace",
        "line_comment": "#",
        "budget": (200, 40, 3, 4),
        "func": re.compile(
            r"^(?P<indent>\s*)(?:function\s+)?(?P<name>[A-Za-z_]\w*)\s*\(\s*\)\s*\{"
        ),
    },
}

SKIP_DIRS = {
    ".git", ".hg", ".svn", "node_modules", "vendor", "dist", "build", "target",
    "__pycache__", ".venv", "venv", ".tox", ".next", ".nuxt", "coverage",
    "migrations", "generated", ".terraform", "Pods",
}

# Names that say nothing about the value they hold.
WEAK_NAMES = {
    "data", "data2", "info", "temp", "tmp", "obj", "val", "val2", "res", "ret",
    "foo", "bar", "baz", "thing", "stuff", "item2", "arr2", "list2", "x1", "y1",
}

GENERATED_MARKERS = (
    "do not edit", "auto-generated", "autogenerated", "code generated by",
    "@generated",
)


@dataclass
class Finding:
    path: str
    line: int
    rule: str
    detail: str


@dataclass
class Budget:
    file_lines: int
    func_lines: int
    depth: int
    params: int


def language_for(path: Path) -> tuple[str, dict] | tuple[None, None]:
    suffix = path.suffix.lower()
    for name, spec in LANGUAGES.items():
        if suffix in spec["ext"]:
            return name, spec
    return None, None


def strip_strings(line: str) -> str:
    """Blank out quoted spans so braces and comments inside them do not count."""
    out = []
    quote = ""
    escaped = False
    for ch in line:
        if quote:
            if escaped:
                escaped = False
            elif ch == "\\":
                escaped = True
            elif ch == quote:
                quote = ""
            out.append(" ")
            continue
        if ch in "\"'`":
            quote = ch
            out.append(" ")
            continue
        out.append(ch)
    return "".join(out)


TRIPLE_RE = re.compile(r'"""|\'\'\'')


def strip_triple_quoted(raw: list[str]) -> list[str]:
    """Blank out triple quoted blocks so docstrings do not count as code lines."""
    out = []
    fence = ""
    for line in raw:
        text = line
        if fence:
            end = text.find(fence)
            if end == -1:
                out.append("")
                continue
            text = text[end + 3:]
            fence = ""
        while True:
            opening = TRIPLE_RE.search(text)
            if not opening:
                break
            closing = text.find(opening.group(0), opening.end())
            if closing == -1:
                fence = opening.group(0)
                text = text[:opening.start()]
                break
            text = text[:opening.start()] + " " + text[closing + 3:]
        out.append(text)
    return out


def clean_lines(raw: list[str], marker: str) -> list[str]:
    """Return lines with strings, docstrings and comments removed."""
    result = []
    in_block = False
    for line in strip_triple_quoted(raw):
        text = line
        if in_block:
            end = text.find("*/")
            if end == -1:
                result.append("")
                continue
            text = text[end + 2:]
            in_block = False
        text = strip_strings(text)
        start = text.find("/*")
        while start != -1:
            end = text.find("*/", start + 2)
            if end == -1:
                text = text[:start]
                in_block = True
                break
            text = text[:start] + " " + text[end + 2:]
            start = text.find("/*")
        cut = text.find(marker)
        result.append(text[:cut] if cut != -1 else text)
    return result


def is_generated(raw: list[str]) -> bool:
    head = "\n".join(raw[:5]).lower()
    return any(marker in head for marker in GENERATED_MARKERS)


def count_code_lines(cleaned: list[str]) -> int:
    return sum(1 for line in cleaned if line.strip())


def indent_of(line: str) -> int:
    return len(line) - len(line.lstrip())


def find_function_end_indent(cleaned: list[str], start: int, base_indent: int) -> int:
    """For indent languages: the last line belonging to the block opened at start."""
    last = start
    for i in range(start + 1, len(cleaned)):
        line = cleaned[i]
        if not line.strip():
            continue
        if indent_of(line) <= base_indent:
            return last
        last = i
    return last


def find_function_end_brace(cleaned: list[str], start: int) -> int:
    """For brace languages: the line where the function's opening brace closes."""
    depth = 0
    opened = False
    for i in range(start, len(cleaned)):
        line = cleaned[i]
        depth += line.count("{")
        if depth > 0:
            opened = True
        depth -= line.count("}")
        if opened and depth <= 0:
            return i
    return len(cleaned) - 1


def statement_indents(cleaned: list[str], start: int, end: int) -> list[int]:
    """Indent column of each line that opens a statement.

    Lines that continue an unclosed bracket are skipped, because a dictionary
    literal or a wrapped call argument is not a nesting level.
    """
    out: list[int] = []
    bracket = 0
    for i in range(start, end + 1):
        line = cleaned[i]
        if not line.strip():
            continue
        if bracket == 0:
            out.append(indent_of(line))
        bracket += line.count("(") + line.count("[") + line.count("{")
        bracket -= line.count(")") + line.count("]") + line.count("}")
        bracket = max(bracket, 0)
    return out


def infer_indent_step(indents: list[int]) -> int:
    """Most common gap between neighbouring indent columns, defaulting to four."""
    widths = sorted(set(indents))
    gaps: dict[int, int] = {}
    for lower, upper in zip(widths, widths[1:]):
        gap = upper - lower
        if 0 < gap <= 8:
            gaps[gap] = gaps.get(gap, 0) + 1
    if not gaps:
        return 4
    return max(gaps.items(), key=lambda kv: (kv[1], -kv[0]))[0]


def max_depth_in(cleaned: list[str], start: int, end: int, block: str) -> int:
    """Deepest nesting inside a function body, counting the body itself as zero."""
    if block == "indent":
        indents = statement_indents(cleaned, start, end)
        if len(indents) < 2:
            return 0
        base = indents[0]
        step = infer_indent_step(indents)
        levels = max((i - base) // step for i in indents)
        return max(levels - 1, 0)
    depth = 0
    peak = 0
    for line in cleaned[start:end + 1]:
        depth += line.count("{")
        peak = max(peak, depth)
        depth -= line.count("}")
    return max(peak - 1, 0)


def count_params(cleaned: list[str], start: int) -> int:
    """Count parameters in the signature, following it across lines if needed."""
    text = " ".join(cleaned[start:start + 6])
    open_at = text.find("(")
    if open_at == -1:
        return 0
    depth = 0
    for i in range(open_at, len(text)):
        if text[i] == "(":
            depth += 1
        elif text[i] == ")":
            depth -= 1
            if depth == 0:
                inner = text[open_at + 1:i]
                break
    else:
        return 0
    inner = re.sub(r"<[^<>]*>", "", inner)
    inner = re.sub(r"\[[^\[\]]*\]", "", inner)
    parts = [p.strip() for p in inner.split(",") if p.strip()]
    return len([p for p in parts if p not in {"self", "cls", "&self", "&mut self"}])


def match_name(match: re.Match) -> str:
    for key in ("name", "name2", "name3"):
        if key in match.groupdict() and match.group(key):
            return match.group(key)
    return "anonymous"


def scan_functions(cleaned: list[str], spec: dict, budget: Budget, path: str) -> list[Finding]:
    """Walk every function in one file and measure it against the budget."""
    findings: list[Finding] = []
    pattern = spec["func"]
    block = spec["block"]
    for i, line in enumerate(cleaned):
        match = pattern.match(line)
        if not match:
            continue
        name = match_name(match)
        if block == "indent":
            end = find_function_end_indent(cleaned, i, indent_of(line))
        else:
            end = find_function_end_brace(cleaned, i)
        body = count_code_lines(cleaned[i:end + 1])
        if body > budget.func_lines:
            findings.append(Finding(path, i + 1, "function-length",
                                    "%s is %d lines, budget %d"
                                    % (name, body, budget.func_lines)))
        depth = max_depth_in(cleaned, i, end, block)
        if depth > budget.depth:
            findings.append(Finding(path, i + 1, "nesting-depth",
                                    "%s nests %d deep, budget %d"
                                    % (name, depth, budget.depth)))
        params = count_params(cleaned, i)
        if params > budget.params:
            findings.append(Finding(path, i + 1, "parameter-count",
                                    "%s takes %d parameters, budget %d"
                                    % (name, params, budget.params)))
    return findings


def scan_names(cleaned: list[str], path: str) -> list[Finding]:
    """Flag identifiers that say nothing about the value they hold."""
    findings: list[Finding] = []
    assign = re.compile(r"\b(?:let|var|const|final)?\s*([A-Za-z_$][\w$]*)\s*(?::[^=]+)?=[^=]")
    for i, line in enumerate(cleaned):
        for match in assign.finditer(line):
            name = match.group(1)
            if name.lower() in WEAK_NAMES:
                findings.append(Finding(path, i + 1, "weak-name",
                                        "%s does not say what the value is" % name))
    return findings


def scan_file(path: Path, overrides: dict, check_names: bool) -> tuple[str, list[Finding]] | None:
    """Measure one file and return its language and every budget finding."""
    language, spec = language_for(path)
    if not spec:
        return None
    try:
        raw = path.read_text(encoding="utf-8").splitlines()
    except (UnicodeDecodeError, OSError):
        return None
    if is_generated(raw):
        return None

    defaults = spec["budget"]
    budget = Budget(
        overrides.get("file") or defaults[0],
        overrides.get("function") or defaults[1],
        overrides.get("depth") or defaults[2],
        overrides.get("params") or defaults[3],
    )
    cleaned = clean_lines(raw, spec["line_comment"])
    code_lines = count_code_lines(cleaned)
    display = path.as_posix()
    findings: list[Finding] = []
    if code_lines > budget.file_lines:
        findings.append(Finding(display, 1, "file-length",
                                "%d code lines, budget %d" % (code_lines, budget.file_lines)))
    findings.extend(scan_functions(cleaned, spec, budget, display))
    if check_names:
        findings.extend(scan_names(cleaned, display))
    return language, findings


def collect(targets: list[str], wanted_ext: set[str]) -> list[Path]:
    """Expand the given paths into a sorted list of source files to read."""
    found: list[Path] = []
    for target in targets:
        base = Path(target)
        if base.is_file():
            found.append(base)
            continue
        if not base.is_dir():
            print("skip (no such path): %s" % target, file=sys.stderr)
            continue
        for path in sorted(base.rglob("*")):
            if not path.is_file():
                continue
            if any(part in SKIP_DIRS for part in path.parts):
                continue
            found.append(path)
    if wanted_ext:
        found = [p for p in found if p.suffix.lower().lstrip(".") in wanted_ext]
    return found


def build_parser() -> argparse.ArgumentParser:
    ap = argparse.ArgumentParser(
        prog="structure_scan.py",
        description="Report code over its file, function, nesting or parameter budget.")
    ap.add_argument("paths", nargs="+", help="files or directories to read")
    ap.add_argument("--max-file", type=int, dest="file", help="override file line budget")
    ap.add_argument("--max-function", type=int, dest="function",
                    help="override function line budget")
    ap.add_argument("--max-depth", type=int, dest="depth", help="override nesting budget")
    ap.add_argument("--max-params", type=int, dest="params",
                    help="override parameter count budget")
    ap.add_argument("--ext", default="", help="comma separated extensions to include")
    ap.add_argument("--names", action="store_true",
                    help="also flag identifiers that say nothing")
    ap.add_argument("--json", action="store_true", help="machine readable output")
    ap.add_argument("--quiet", action="store_true", help="print only the summary")
    return ap


def main(argv: list[str]) -> int:
    args = build_parser().parse_args(argv)
    overrides = {
        "file": args.file, "function": args.function,
        "depth": args.depth, "params": args.params,
    }
    wanted = {e.strip().lstrip(".").lower() for e in args.ext.split(",") if e.strip()}
    files = collect(args.paths, wanted)
    if not files:
        print("no source files found", file=sys.stderr)
        return 2

    reports = [r for r in (scan_file(p, overrides, args.names) for p in files) if r]
    findings = [f for _, group in reports for f in group]

    if args.json:
        print(json.dumps(
            [{"path": f.path, "line": f.line, "rule": f.rule, "detail": f.detail}
             for f in findings], indent=2))
        return 1 if findings else 0

    if not args.quiet:
        for f in sorted(findings, key=lambda f: (f.path, f.line)):
            print("%s:%d  [%s] %s" % (f.path, f.line, f.rule, f.detail))

    print("\nread %d file(s) in %d language(s), %d finding(s)"
          % (len(reports), len({lang for lang, _ in reports}), len(findings)))
    return 1 if findings else 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
